### ISSUE TITLE
Username/password aren't cleared after logout

### ISSUE THREAD

**Issue by jcf** [fulcro-legacy/fulcro-template#4]
This maybe isn't an issue in a demo app, but `:ui/username` and `:ui/password` aren't cleared out when you log out, so you can click login without entering anything in the login form and get back into the app.

 If anyone uses this code as a starting point for his or her application, that's a pretty serious security issue on a shared machine.

I was hoping to send over a PR to fix this by transacting `{:ui/username "", :ui/password ""}` into the app state (it probably makes sense to always reset the password on form submission?), but I wasn't sure if pushing things into `[:pages :current-route]` was the right thing to do given the route is about to change/has just changed.

**Comment by awkay** [comment]
Hi, Yeah, it is just a demo but you're right, there are a number of things that should be tightened up: the password ends up in the logs. I agree that the creds should be cleared on success. The route doesn't matter, since the component has an ident. I'd have to look more carefully (I'm on the road), but there is a tempid remap, so it might be a matter of looking for the (one and only) user in the table and patching it.

**Comment by jcf** [comment]
I'd love to see where/how you fix this; I'm not an expert on om.next (yet :wink:).

Feel free to close this one down if you want. I'll leave it open on the assumption it's a good place to keep track of progress…?

**Comment by jcf** [comment]
Oh, and thanks again Tony!

**Comment by awkay** [comment]
The controls were also not controlled...so, I fixed both. On develop and master.
